# MongoDB connection information
database:
  host: "104.248.211.207"
  port: 8010
  user: "user"
  password: "8b75605be"
  db: "rhodiumcoin_bot"

# Discord Bot user token
discord:
  token: "NTMzNDc2NTAyNDAzMTUzOTIw.D1Xxwg"

# walletd connection information
wallet:
  host: "127.0.0.1"
  port: "8004"

# RHOX is 8-digit, 100000000
tx_fee: 1410000000
min_tx_amount: 100000000
max_tx_amount: 2000000000000000

# How many seconds between balance refresh with zedwallet
wallet_balance_update_interval: 30
